#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


function enable_reith() {
  export http_proxy="http://www-cache.reith.bbc.co.uk:80"
  export https_proxy="http://www-cache.reith.bbc.co.uk:80"
  export ftp_proxy="ftp-gw.reith.bbc.co.uk:21"
  export socks_proxy="socks-gw.reith.bbc.co.uk:1085"

  export HTTP_PROXY="http://www-cache.reith.bbc.co.uk:80"
  export HTTPS_PROXY="http://www-cache.reith.bbc.co.uk:80"
  export FTP_PROXY="ftp-gw.reith.bbc.co.uk:21"
  export SOCKS_PROXY="socks-gw.reith.bbc.co.uk:1085"
}

function disable_reith() {
  unset http_proxy
  unset https_proxy
  unset ftp_proxy
  unset socks_proxy

  unset HTTP_PROXY
  unset HTTPS_PROXY
  unset FTP_PROXY
  unset SOCKS_PROXY
}

alias reith="source /Users/clarkjw1/proxyconfig/reith"
echo "Enabling proxy config for reith..."
reith

export NVM_DIR="$HOME/.nvm"
. "$(brew --prefix nvm)/nvm.sh"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

#GPG Agent
if [[ $(uname) == Darwin ]]; then
  if [ -f "${HOME}/.gpg-agent-info" ]; then
    . "${HOME}/.gpg-agent-info"
    export GPG_AGENT_INFO
    export SSH_AUTH_SOCK
  fi
fi

export GPG_TTY=$(tty)
