#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export NVM_DIR="$HOME/.nvm"
. "$(brew --prefix nvm)/nvm.sh"

#GPG Agent
# Invoke GnuPG-Agent the first time we login.
# Does `~/.gpg-agent-info' exist and points to gpg-agent process accepting signals?
[ -f ~/.gnupg/gpg-agent.env ] && source ~/.gnupg/gpg-agent.env
if [ -S "${GPG_AGENT_INFO%%:*}" ]; then
  echo "Configuring running GPG"
  export GPG_AGENT_INFO
  export GPG_TTY=`tty`
  export SSH_AUTH_SOCK
else
  echo "Starting GPG Agent..."
  eval $(gpg-agent --daemon --log-file /tmp/gpg.log --no-grab --enable-ssh-support --write-env-file ~/.gnupg/gpg-agent.env)
fi
